apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
      - name: capstone-project
        image: viveknig9/capstone-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: capstone-project